// Generated by CoffeeScript 1.9.3
(function() {
  var arrayDos, arrayUno, i, item, len;

  arrayUno = [2, 5, 6, 'hola', 'luis'];

  arrayDos = [1, 2, 3, 4, 5];


  /*
  #Mostrar un elemento de arreglo
  console.log arrayDos[3]
  
  #Agregar elementos al final del arreglo
  arrayDos.push 6,7,8
  console.log arrayDos
  
  #Agregar elementos al inicio del arreglo
  arrayUno.unshift 3,-2,-1,0 
  console.log arrayUno
  
  #Eliminar ultimo elemento del arreglo
  console.log arrayUno.pop()
  
  #Eliminar un elemento en especifico del arreglo
  console.log arrayUno.pop('hola')
  
  #Eliminar primer elemento del arreglo
  console.log arrayUno.shift()
  
  console.log arrayUno
   */

  for (i = 0, len = arrayDos.length; i < len; i++) {
    item = arrayDos[i];
    console.log(item);
  }

}).call(this);
