// Generated by CoffeeScript 1.9.3
(function() {
  var input, password;

  password = "luis";

  while (true) {
    input = prompt("What's the correct password");
    if (input === password) {
      break;
    }
  }

}).call(this);
