// Generated by CoffeeScript 1.9.3

/* recorre un rango del 1 al 10 e imprime los que son mayores a 5
for number in [1..10] when number > 5
    console.log number
 */


/* recorre un rango del 0 al 100 e imprime de 10 en 10
for number in [0..100] by 10
    console.log number
 */

(function() {
  var evenNumber, number;

  evenNumber = (function() {
    var i, results;
    results = [];
    for (number = i = 1; i <= 100; number = ++i) {
      if (number % 2 === 0) {
        results.push(number);
      }
    }
    return results;
  })();

  console.log(evenNumber);

}).call(this);
