// Generated by CoffeeScript 1.9.3
(function() {
  var array, array_product, shopping_list;

  shopping_list = function(array) {
    var addList, i, item, len;
    addList = '<ul>';
    for (i = 0, len = array.length; i < len; i++) {
      item = array[i];
      addList += "<li>" + item[0] + " $" + item[1] + "</li>";
    }
    addList += '</ul>';
    return document.write(addList);
  };

  array = [];

  while (true) {
    array_product = [];
    array_product.push(prompt("Enter any product!!"));
    array_product.push(prompt("Enter it's price"));
    if (array_product[0] && array_product[1]) {
      array.push(array_product);
    } else {
      break;
    }
  }

  shopping_list(array);

}).call(this);
