// Generated by CoffeeScript 1.9.3
(function() {
  var array_thing, i, item, len, thing;

  array_thing = [];

  while (true) {
    thing = prompt("Enter any product!!");
    if (thing === '') {
      break;
    }
    array_thing.push(thing);
  }

  console.log(array_thing);

  document.write('<ul>');

  for (i = 0, len = array_thing.length; i < len; i++) {
    item = array_thing[i];
    document.write("<li> " + item + " </li>");
  }

  document.write('</ul>');

}).call(this);
